version: '2.2'
services:

  elasticsearchhub:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9222:9200

volumes:
  esdatahub:
    driver: local
